# Site settings
title: A Full-Stack of Pancakes
header-img: img/home-bg.png
email: lukey.mac@outlook.com
copyright_name: Lucas Kisabeth
description: > # this means to ignore newlines until "baseurl:"
  My Journey as a Full-Stack Web Developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username:
github_username:  lkisabeth
learn_profile: lukeymac
email_username: lukey.mac@outlook.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
